### ISSUE TITLE
Not working with the latest wgpu and imgui

### ISSUE THREAD

**Issue by varomix** [aloucks/imgui-glfw-support#3]
Using the current versions the simple example doesn't work
Wgpu changed some stuff and seems like imgui did as well

would be nice to update it

thank you

**Comment by aloucks** [comment]
Version [0.4.0](https://crates.io/crates/imgui-glfw-support/0.4.0) has been published with support for the latest `glfw` and `imgui` crates and the examples now use the latest `wgpu`.

**Comment by varomix** [comment]
amazing, thank you
