### ISSUE TITLE
Index out of bounds: with io.key_down[] when key: Glfw::Key == -1

### ISSUE THREAD

**Issue by exrok** [aloucks/imgui-glfw-support#4]
See, https://github.com/aloucks/imgui-glfw-support/blob/412ca4b49dd95add09d9fb46f79c7b6f299e92f9/src/lib.rs#L158-L163

Glfw::Key as usize may be much larger than 512 as Key::Unknown = -1. 

If I hit the hyper key on my keyboard:
```
thread 'main' panicked at 'index out of bounds:
 the len is 512 but the index is 18446744073709551615', 
.../imgui-glfw-support-0.4.0/src/lib.rs:162:21
```
My workaround for now:
```
match event {
    WindowEvent::Key(Key::Unknown,..) => (), //workaround bug in imgui-glfw-support-0.4.0
    _ => glfw_platform.handle_event(io, &app.window, &event)
};
```
I think ignoring unknown key inside the library itself is an acceptable solution. 

Edit: Acknowledge Key::Unknown as the problem.

**Comment by aloucks** [comment]
@exrok Can you verify that this branch resolves your issue: https://github.com/aloucks/imgui-glfw-support/tree/issue-4

**Comment by exrok** [comment]
https://github.com/aloucks/imgui-glfw-support/tree/issue-4 does solve the issue. Thank you.

**Comment by aloucks** [comment]
@exrok 

Version [0.4.1](https://crates.io/crates/imgui-glfw-support/0.4.1) has been published.
